#!/usr/bin/env bash
# Installs nginx server


sudo apt-get update
sudo apt-get install nginx
sudo ufw enable 
sudo ufw app list
sudo ufw allow 80
sudo echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
sudu service nginx status
