#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string  "Ceci n'est pas une page"

sudo apt-get update
sudo apt-get install nginx

echo "Ceci n'est pas une page" > /var/www/html/404.html
error_page 404 /404.html;
location = /404-not_found_page_404.html;
root /var/www/html
internal;
sudo sed -i listen 80 default_server;

# restart the server
sudo service nginx restart
